# Use the official mcr.microsoft.com/dotnet/runtime:6.0-focal image for .NET 6.0 SDK and Ubuntu base image
FROM mcr.microsoft.com/dotnet/runtime:6.0-focal

# Install Supervisor
RUN apt-get update && \
    apt-get install -y supervisor && \
    rm -rf /var/lib/apt/lists/*

# .NET Core Tools
RUN dotnet tool install --global dotnet-monitor
RUN dotnet tool install --global dotnet-counters
RUN dotnet tool install --global dotnet-dump

# Add .NET Core Tools to PATH
ENV PATH="/root/.dotnet/tools:${PATH}"
ENV ASPNETCORE_ENVIRONMENT=Development      
ENV ASPNETCORE_URLS=http://*:80
ENV COMPlus_DbgMiniDumpType=4
ENV COMPlus_DbgEnableMiniDump=1
ENV COMPlus_DbgMiniDumpName=/app/dumpfiles/coredump-%p-%e-%t.dmp

# Start Supervisor
CMD ["/usr/bin/supervisord"]
